version: "3.9"

services:
  mongodb:
    image: mongo:5.0.10
    container_name: mongodb
    restart: unless-stopped
    volumes:
      - mongo-data:/data/db
    ports:
      - 27017:27017

  redis:
    image: bitnami/redis:6.2.6
    container_name: redis
    restart: unless-stopped
    environment:
      REDIS_HOST: localhost
      ALLOW_EMPTY_PASSWORD: "yes"
    ports:
      - "6379:6379"

volumes:
  mongo-data:
    driver: local
